//! Agent-Verifiable Context (AVC) — Structured truth contracts for AI agents
//!
//! The AVC is NOT a comment. It's a machine-verifiable structured object
//! generated by the Rust engine that the AI agent MUST comply with.
//!
//! Three layers of verification:
//! 1. Syntax Contract (Tree-sitter): exact types, dependencies, forbidden patterns
//! 2. Semantic Alignment (BM25): intent score, domain vocabulary, drift detection
//! 3. Safety Invariants (Rust types): ownership, error handling, lifetime rules

use serde::{Deserialize, Serialize};

/// The complete Agent-Verifiable Context contract.
/// Generated by the engine BEFORE the agent writes code.
/// Validated AGAINST the agent's output AFTER generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AvcContract {
    /// Unique contract identifier
    pub contract_id: String,
    /// The source of truth file this contract is based on
    pub source_of_truth: String,
    /// Human-readable description of what this contract enforces
    pub description: String,
    /// Syntax-level constraints (Tree-sitter extracted)
    pub syntax: SyntaxContract,
    /// Semantic alignment constraints (BM25 scored)
    pub semantic: SemanticContract,
    /// Safety invariants that must hold
    pub safety: SafetyContract,
    /// Depth of context provided (1 = function only, 2 = +struct, 3 = +dependencies)
    pub context_depth: u8,
}

// ─────────────────────────────────────────────────────────────────────────────
// Layer 1: Syntax Contract (Tree-sitter)
// ─────────────────────────────────────────────────────────────────────────────

/// Exact types and patterns extracted from the codebase via Tree-sitter.
/// The agent MUST use these exact types, not invent new ones.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyntaxContract {
    /// Programming language
    pub language: String,
    /// Required types that the function MUST use (extracted from codebase)
    pub required_types: Vec<TypeRequirement>,
    /// Function signatures that must be called
    pub required_calls: Vec<RequiredCall>,
    /// AST patterns that are FORBIDDEN (unsafe, panic, unwrap)
    pub forbidden_patterns: Vec<String>,
    /// The function being contracted
    pub target_function: Option<FunctionSignature>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeRequirement {
    pub name: String,
    pub kind: TypeKind,
    pub definition_file: String,
    pub definition_line: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TypeKind {
    Struct,
    Enum,
    Trait,
    TypeAlias,
    Function,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequiredCall {
    pub function_name: String,
    pub file: String,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionSignature {
    pub name: String,
    pub params: Vec<ParamInfo>,
    pub return_type: String,
    pub file: String,
    pub line: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParamInfo {
    pub name: String,
    pub type_name: String,
    pub is_mutable: bool,
    pub is_reference: bool,
}

// ─────────────────────────────────────────────────────────────────────────────
// Layer 2: Semantic Contract (BM25)
// ─────────────────────────────────────────────────────────────────────────────

/// Semantic alignment check using BM25.
/// Detects "lies" — when the function name says one thing but the code does another.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SemanticContract {
    /// The intended purpose of this code (extracted from name + docstring)
    pub intent: String,
    /// Minimum BM25 similarity score required between intent and implementation
    /// Below this threshold = SEMANTIC DRIFT detected
    pub bm25_threshold: f32,
    /// Terms that statistically belong to this domain (from training on codebase)
    pub domain_terms: Vec<String>,
    /// Terms that are FORBIDDEN in this context (would indicate drift)
    pub forbidden_terms: Vec<String>,
    /// Current BM25 score (populated during validation)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_score: Option<f32>,
    /// Whether the contract passed the semantic check
    #[serde(skip_serializing_if = "Option::is_none")]
    pub semantic_pass: Option<bool>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Layer 3: Safety Contract (Rust types)
// ─────────────────────────────────────────────────────────────────────────────

/// Safety invariants that the agent's code MUST satisfy.
/// Violating these = the contract is broken.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafetyContract {
    /// Invariants that must be true at all times
    pub invariants: Vec<String>,
    /// If the function returns Result, error handling is MANDATORY
    pub requires_error_handling: bool,
    /// Ownership rules: who owns what
    pub ownership_rules: Vec<OwnershipRule>,
    /// Lifetime requirements
    pub lifetime_requirements: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OwnershipRule {
    pub description: String,
    pub resource: String,
    pub owner: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation Result
// ─────────────────────────────────────────────────────────────────────────────

/// Result of validating agent-generated code against an AVC contract
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AvcValidationResult {
    /// Overall pass/fail
    pub passed: bool,
    /// Contract ID that was validated
    pub contract_id: String,
    /// Per-layer results
    pub syntax_check: LayerResult,
    pub semantic_check: LayerResult,
    pub safety_check: LayerResult,
    /// Specific violations found (so the agent can fix them)
    pub violations: Vec<AvcViolation>,
    /// Suggested fixes for each violation
    pub suggestions: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LayerResult {
    pub layer: String,
    pub passed: bool,
    pub score: f32,
    pub details: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AvcViolation {
    pub layer: String,
    pub severity: ViolationSeverity,
    pub message: String,
    pub location: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ViolationSeverity {
    /// Contract cannot be satisfied — generation should be blocked
    Blocker,
    /// Suspicious but might be intentional — requires agent explanation
    Warning,
    /// Minor deviation — auto-fixable
    Info,
}

// ─────────────────────────────────────────────────────────────────────────────
// Builder pattern for AVC contracts
// ─────────────────────────────────────────────────────────────────────────────

impl AvcContract {
    pub fn new(id: impl Into<String>, source: impl Into<String>) -> Self {
        Self {
            contract_id: id.into(),
            source_of_truth: source.into(),
            description: String::new(),
            syntax: SyntaxContract {
                language: "rust".to_string(),
                required_types: Vec::new(),
                required_calls: Vec::new(),
                forbidden_patterns: vec![
                    "unsafe".to_string(),
                    "panic!".to_string(),
                    ".unwrap()".to_string(),
                    ".expect(".to_string(),
                ],
                target_function: None,
            },
            semantic: SemanticContract {
                intent: String::new(),
                bm25_threshold: 0.7,
                domain_terms: Vec::new(),
                forbidden_terms: Vec::new(),
                current_score: None,
                semantic_pass: None,
            },
            safety: SafetyContract {
                invariants: Vec::new(),
                requires_error_handling: true,
                ownership_rules: Vec::new(),
                lifetime_requirements: Vec::new(),
            },
            context_depth: 2,
        }
    }

    pub fn with_description(mut self, desc: impl Into<String>) -> Self {
        self.description = desc.into();
        self
    }

    pub fn with_intent(mut self, intent: impl Into<String>) -> Self {
        self.semantic.intent = intent.into();
        self
    }

    pub fn with_threshold(mut self, threshold: f32) -> Self {
        self.semantic.bm25_threshold = threshold;
        self
    }

    pub fn with_domain_terms(mut self, terms: Vec<String>) -> Self {
        self.semantic.domain_terms = terms;
        self
    }

    pub fn with_forbidden_terms(mut self, terms: Vec<String>) -> Self {
        self.semantic.forbidden_terms = terms;
        self
    }

    pub fn with_forbidden_patterns(mut self, patterns: Vec<String>) -> Self {
        self.syntax.forbidden_patterns = patterns;
        self
    }

    pub fn with_invariants(mut self, invariants: Vec<String>) -> Self {
        self.safety.invariants = invariants;
        self
    }

    pub fn with_required_types(mut self, types: Vec<TypeRequirement>) -> Self {
        self.syntax.required_types = types;
        self
    }

    pub fn with_target_function(mut self, sig: FunctionSignature) -> Self {
        self.syntax.target_function = Some(sig);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_auth_contract() {
        let contract = AvcContract::new("auth-001", "src/auth/session.rs")
            .with_description("User authentication handler")
            .with_intent("secure_authentication")
            .with_threshold(0.85)
            .with_domain_terms(vec![
                "bcrypt".into(), "session_store".into(), "expiry".into()
            ])
            .with_forbidden_terms(vec![
                "password_plain".into(), "base64".into()
            ])
            .with_invariants(vec![
                "No logs of raw passwords".into(),
                "Function must return Result<Session, AuthError>".into(),
            ]);

        assert_eq!(contract.contract_id, "auth-001");
        assert_eq!(contract.semantic.intent, "secure_authentication");
        assert_eq!(contract.semantic.bm25_threshold, 0.85);
        assert_eq!(contract.safety.invariants.len(), 2);
        assert!(contract.safety.requires_error_handling);
        assert!(contract.syntax.forbidden_patterns.contains(&"unsafe".to_string()));
    }

    #[test]
    fn test_contract_serialization() {
        let contract = AvcContract::new("test-001", "test.rs")
            .with_intent("data_processing");

        let json = serde_json::to_string_pretty(&contract).unwrap();
        assert!(json.contains("test-001"));
        assert!(json.contains("data_processing"));

        let deserialized: AvcContract = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.contract_id, "test-001");
    }
}
