#!/bin/bash
sed -i -e '/use walkdir::WalkDir;/d' src/application/services/analysis_service.rs

awk '
/pub fn build_project_graph/ {
    print "    pub fn build_project_graph(&self, project_dir: &Path) -> AppResult<()> {"
    print "        use rayon::prelude::*;"
    print "        use ignore::WalkBuilder;"
    print "        "
    print "        let mut store = PetGraphStore::new();"
    print "        let mut name_to_symbol_id: std::collections::HashMap<String, SymbolId> ="
    print "            std::collections::HashMap::new();"
    print ""
    print "        let files: Vec<_> = WalkBuilder::new(project_dir)"
    print "            .hidden(true)"
    print "            .git_ignore(true)"
    print "            .git_exclude(true)"
    print "            .build()"
    print "            .filter_map(|e| e.ok())"
    print "            .filter(|e| e.path().is_file())"
    print "            .map(|e| {"
    print "                let path = e.path().to_path_buf();"
    print "                let language = Language::from_extension(path.extension());"
    print "                let file_path = path.to_string_lossy().into_owned();"
    print "                let mtime = std::fs::metadata(&path)"
    print "                    .ok()"
    print "                    .and_then(|m| m.modified().ok())"
    print "                    .map(|t| t.duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs())"
    print "                    .unwrap_or(0);"
    print "                (path, language, file_path, mtime)"
    print "            })"
    print "            .filter(|(_, lang, _, _)| lang.is_some())"
    print "            .collect();"
    print ""
    print "        let results: Vec<_> = files.into_par_iter().filter_map(|(path, language, file_path, mtime)| {"
    print "            let language = language.unwrap();"
    print "            "
    print "            {"
    print "                let cache = self.file_cache.lock().unwrap();"
    print "                if let Some((cached_mtime, cached_symbols, cached_relationships)) = cache.get(&file_path) {"
    print "                    if *cached_mtime == mtime {"
    print "                        return Some((file_path, mtime, cached_symbols.clone(), cached_relationships.clone()));"
    print "                    }"
    print "                }"
    print "            }"
    print ""
    print "            let source = std::fs::read_to_string(&path).ok()?;"
    print "            let parser = TreeSitterParser::new(language.clone()).ok()?;"
    print "            "
    print "            let symbols = parser.find_all_symbols_with_path(&source, &file_path).unwrap_or_default();"
    print "            let relationships = parser.find_call_relationships(&source, &file_path).unwrap_or_default();"
    print "            "
    print "            Some((file_path, mtime, symbols, relationships))"
    print "        }).collect();"
    print ""
    print "        let mut cache = self.file_cache.lock().unwrap();"
    print "        let mut all_relationships = Vec::new();"
    print "        "
    print "        for (file_path, mtime, symbols, relationships) in results {"
    print "            cache.insert(file_path.clone(), (mtime, symbols.clone(), relationships.clone()));"
    print "            "
    print "            for symbol in symbols {"
    print "                let symbol_id = SymbolId::new(symbol.fully_qualified_name());"
    print "                store.add_symbol_with_location(&symbol_id, symbol.clone());"
    print "                name_to_symbol_id.insert(symbol.name().to_lowercase(), symbol_id);"
    print "            }"
    print "            "
    print "            for (caller, callee_name) in relationships {"
    print "                all_relationships.push((caller, callee_name));"
    print "            }"
    print "        }"
    print "        "
    print "        for (caller, callee_name) in all_relationships {"
    print "            let caller_id = SymbolId::new(caller.fully_qualified_name());"
    print "            if let Some(callee_id) = name_to_symbol_id.get(&callee_name.to_lowercase()) {"
    print "                store.add_dependency(&caller_id, callee_id, DependencyType::Calls).ok();"
    print "            }"
    print "        }"
    print ""
    print "        let call_graph = store.to_call_graph();"
    print "        self.graph_cache.set(call_graph);"
    print ""
    print "        Ok(())"
    print "    }"
    in_func = 1
    next
}
in_func && /^    pub fn get_project_graph/ {
    in_func = 0
}
!in_func {
    print
}
' src/application/services/analysis_service.rs > src/application/services/analysis_service.rs.tmp

mv src/application/services/analysis_service.rs.tmp src/application/services/analysis_service.rs
