[package]
name = "cognicode-cli"
description = "CogniCode CLI"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "cognicode"
path = "src/main.rs"

[[bin]]
name = "cogh"
path = "src/bin/cogh.rs"

[dependencies]
cognicode-core.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
toml.workspace = true
sha2.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
reqwest.workspace = true
tar.workspace = true
flate2.workspace = true
dirs = "5"
rayon.workspace = true
