//! Pages module
pub mod agent_stats;
pub mod configuration;
pub mod contracts;
pub mod dashboard;
pub mod drift;
pub mod issue_detail;
pub mod issues;
pub mod metrics;
pub mod not_found;
pub mod projects;
pub mod quality_gate;

pub use agent_stats::AgentStatsPage;
pub use configuration::ConfigurationPage;
pub use contracts::ContractsPage;
pub use dashboard::DashboardPage;
pub use drift::DriftPage;
pub use issue_detail::IssueDetailPage;
pub use issues::IssuesPage;
pub use metrics::MetricsPage;
pub use not_found::NotFoundPage;
pub use projects::ProjectsPage;
pub use quality_gate::QualityGatePage;