//! STYLE_002 — Inconsistent naming conventions within a file
//!
//! Detects when a file contains a mixture of naming conventions (snake_case and camelCase)
//! for similar items (functions, variables, etc.).
//!
//! ## Naming Conventions
//! - `snake_case`: lowercase with underscores (e.g., `my_variable`)
//! - `camelCase`: lowercase start, uppercase words (e.g., `myVariable`)
//! - `PascalCase`: uppercase start (e.g., `MyStruct`)
//! - `SCREAMING_SNAKE_CASE`: uppercase with underscores (e.g., `MY_CONSTANT`)
//!
//! ## False Positives
//! - External/library API calls (cannot control their naming)
//! - Generated code (build outputs, protobuf outputs)
//! - Constants written in UPPER_SNAKE_CASE (valid exception)
//! - Files with only 1-2 identifiers (insufficient sample)
//! - Generated code markers like "// GENERATED CODE"
use crate::{Severity, Category, Issue, Remediation, Rule, RuleContext, RuleEntry};
use crate::rules::{CleanCodeAttribute, SoftwareQuality, SoftwareQualityImpact, ImpactSeverity};
use cognicode_macros::declare_rule;
use inventory::submit;
use streaming_iterator::StreamingIterator;

/// Minimum identifiers of each convention needed to confirm intentional mixing
const THRESHOLD_COUNT: usize = 3;

/// Markers that indicate a file is generated
const GENERATED_MARKERS: &[&str] = &[
    "// GENERATED",
    "# GENERATED",
    "/* GENERATED",
    "// This file is generated",
    "# This file is generated",
    "// Automatically generated",
    "# Automatically generated",
    "// Code generated by",
    "# Code generated by",
    "@generated",
];

/// Classification of naming conventions
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NamingConvention {
    SnakeCase,
    CamelCase,
    PascalCase,
    ScreamingSnakeCase,
    Unknown,
}

impl NamingConvention {
    /// Classify a name into its naming convention
    fn classify(name: &str) -> Self {
        if name.is_empty() {
            return NamingConvention::Unknown;
        }

        // SCREAMING_SNAKE_CASE: all uppercase with underscores, numbers allowed
        if name.chars().all(|c| c.is_uppercase() || c == '_' || c.is_numeric())
            && name.contains('_')
            && !name.chars().take(1).all(|c| c.is_numeric())
        {
            return NamingConvention::ScreamingSnakeCase;
        }

        let has_underscore = name.contains('_');
        let has_uppercase = name.chars().any(|c| c.is_uppercase());

        // Check if it starts with uppercase (PascalCase)
        let starts_uppercase = name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false);

        if starts_uppercase {
            // Could be PascalCase or acronym
            if has_underscore {
                // Mix of PascalCase and underscore suggests inconsistent style
                NamingConvention::Unknown
            } else if has_uppercase {
                // It's PascalCase if it has uppercase in the middle
                if name.chars().skip(1).any(|c| c.is_uppercase()) {
                    NamingConvention::PascalCase
                } else {
                    // Single uppercase letter at start might be an abbreviation
                    NamingConvention::PascalCase
                }
            } else {
                NamingConvention::PascalCase
            }
        } else {
            // Starts with lowercase
            if has_underscore && has_uppercase {
                // Mix of underscores and uppercase is inconsistent
                NamingConvention::Unknown
            } else if has_underscore {
                NamingConvention::SnakeCase
            } else if has_uppercase {
                // camelCase has uppercase but no underscores, and doesn't start with uppercase
                NamingConvention::CamelCase
            } else {
                // All lowercase with no underscore - could be a simple name
                NamingConvention::SnakeCase
            }
        }
    }

    fn as_str(&self) -> &'static str {
        match self {
            NamingConvention::SnakeCase => "snake_case",
            NamingConvention::CamelCase => "camelCase",
            NamingConvention::PascalCase => "PascalCase",
            NamingConvention::ScreamingSnakeCase => "SCREAMING_SNAKE_CASE",
            NamingConvention::Unknown => "unknown",
        }
    }
}

/// Check if the file appears to be generated
fn is_generated_file(source: &str) -> bool {
    for line in source.lines().take(10) {
        let trimmed = line.trim();
        for marker in GENERATED_MARKERS {
            if trimmed.contains(marker) {
                return true;
            }
        }
    }
    false
}

/// Collect all identifiers from the AST using tree-sitter queries
fn collect_identifiers(ctx: &RuleContext) -> Vec<(String, NamingConvention, usize)> {
    let mut identifiers = Vec::new();

    // Language-specific identifier node kinds
    let identifier_kinds = match ctx.language.name() {
        "JavaScript" | "TypeScript" => vec![
            "identifier",
            "property_identifier",
            "variable_declarator",
        ],
        "Python" => vec![
            "identifier",
            "attribute",
        ],
        _ => vec!["identifier"],
    };

    // Use a generic query to find all identifier-like nodes
    let query_pattern = format!(
        "(identifier) @id"
    );

    if let Ok(query) = tree_sitter::Query::new(&ctx.language.to_ts_language(), &query_pattern) {
        let mut cursor = tree_sitter::QueryCursor::new();
        let mut matches = cursor.matches(&query, ctx.tree.root_node(), ctx.source.as_bytes());

        while let Some(m) = matches.next() {
            for capture in m.captures {
                let node = capture.node;
                if let Ok(name) = node.utf8_text(ctx.source.as_bytes()) {
                    let line = node.start_position().row + 1;
                    let convention = NamingConvention::classify(name);

                    // Skip single character names (likely loop counters)
                    if name.len() <= 1 {
                        continue;
                    }

                    // Skip names that are all lowercase but have no underscore
                    // (they might be regular words, not identifiers)
                    if convention == NamingConvention::SnakeCase
                        && !name.contains('_')
                        && name.chars().all(|c| c.is_lowercase())
                        && name.len() < 3
                    {
                        continue;
                    }

                    identifiers.push((name.to_string(), convention, line));
                }
            }
        }
    }

    identifiers
}

declare_rule! {
    id: "STYLE_002"
    name: "Inconsistent naming conventions within a file"
    severity: Minor
    category: CodeSmell
    language: "javascript,typescript,python"
    params: {
        threshold: usize = 3
    }

    explanation: "When a file contains a mixture of naming conventions (snake_case and camelCase), it violates consistency principles and increases cognitive load. All identifiers within a file should follow the same naming convention. The threshold of 3+ identifiers of each convention is required to confirm mixing is intentional, not accidental."
    clean_code: Focused,
    impacts: [Maintainability: Low],
    auto_test: true

    agent_semantics: {
        summary: "Mixed naming conventions detected - all identifiers should follow consistent style",
        fix_playbook: "1. Identify which naming convention is appropriate for the language\n2. List all identifiers that don't follow the convention\n3. Use IDE refactoring to rename identifiers consistently\n4. Ensure snake_case Python code doesn't mix with camelCase\n5. For JavaScript/TypeScript: ensure functions/variables use camelCase",
        review_questions: [
            "Is this file imported from external source?",
            "Is this code in transition between conventions?",
            "Which convention should be used for this language?",
            "Are there at least 3 instances of each convention to confirm mixing?"
        ],
        semantic_chunks: [
            "Inconsistent naming conventions increase cognitive load",
            "Python should use snake_case; JavaScript/TypeScript should use camelCase",
            "Mixed conventions in same file suggest incomplete refactoring or external imports",
            "Fix: Choose appropriate convention and refactor all identifiers to match"
        ],
        safe_autofix: false,
        autofix_guidance: "Cannot safely autofix without context - requires choosing correct convention and ensuring external APIs are not broken"
    }

    check: => {
        let mut issues = Vec::new();

        // Skip generated files
        if is_generated_file(ctx.source) {
            return issues;
        }

        // Collect all identifiers
        let identifiers = collect_identifiers(ctx);

        // Filter out SCREAMING_SNAKE_CASE constants (valid exception)
        let filtered: Vec<_> = identifiers.into_iter()
            .filter(|(name, convention, _)| {
                // Skip SCREAMING_SNAKE_CASE constants
                if *convention == NamingConvention::ScreamingSnakeCase {
                    return false;
                }
                // Note: We don't filter "external" calls here because we can't reliably
                // distinguish library calls from user-defined functions without scope info.
                // The inconsistency detection relies on threshold counting instead.
                true
            })
            .collect();

        if filtered.len() < self.threshold {
            // Not enough identifiers to determine inconsistency
            return issues;
        }

        // Count identifiers by convention
        let mut convention_counts: std::collections::HashMap<NamingConvention, Vec<(String, usize)>> =
            std::collections::HashMap::new();

        for (name, convention, line) in &filtered {
            if *convention != NamingConvention::Unknown {
                convention_counts.entry(*convention)
                    .or_default()
                    .push((name.clone(), *line));
            }
        }

        // Need at least 2 different conventions to have inconsistency
        let conventions: Vec<_> = convention_counts.keys().collect();
        if conventions.len() < 2 {
            return issues;
        }

        // Find the dominant convention (most identifiers)
        let mut convention_vec: Vec<_> = convention_counts.iter().collect();
        convention_vec.sort_by(|a, b| b.1.len().cmp(&a.1.len()));

        let threshold = self.threshold;
        let dominant = convention_vec[0];
        let dominant_convention = *dominant.0;
        let dominant_count = dominant.1.len();

        // If dominant convention doesn't have threshold+, we can't determine inconsistency
        if dominant_count < threshold {
            return issues;
        }

        // Report issues for each non-dominant convention's identifiers
        for (conv, items) in &convention_counts {
            if *conv == dominant_convention {
                continue;
            }

            for (name, line) in items {
                issues.push(Issue::new(
                    "STYLE_002",
                    format!(
                        "Inconsistent naming: '{}' follows {} but other items use {}",
                        name,
                        conv.as_str(),
                        dominant_convention.as_str()
                    ),
                    Severity::Minor,
                    Category::CodeSmell,
                    ctx.file_path,
                    *line,
                ).with_remediation(Remediation::moderate(
                    format!(
                        "Use consistent naming convention. Consider changing '{}' to match {} style.",
                        name,
                        dominant_convention.as_str()
                    )
                )));
            }
        }

        issues
    }
}

inventory::submit! {
    RuleEntry {
        factory: || Box::new(STYLE_002Rule::new())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_naming_convention_classification() {
        // snake_case
        assert_eq!(NamingConvention::classify("my_variable"), NamingConvention::SnakeCase);
        assert_eq!(NamingConvention::classify("user_id"), NamingConvention::SnakeCase);
        assert_eq!(NamingConvention::classify("get_user_by_id"), NamingConvention::SnakeCase);
        assert_eq!(NamingConvention::classify("get_user_id"), NamingConvention::SnakeCase);
        assert_eq!(NamingConvention::classify("user_name"), NamingConvention::SnakeCase);

        // camelCase
        assert_eq!(NamingConvention::classify("myVariable"), NamingConvention::CamelCase);
        assert_eq!(NamingConvention::classify("userId"), NamingConvention::CamelCase);
        assert_eq!(NamingConvention::classify("getUserById"), NamingConvention::CamelCase);

        // PascalCase
        assert_eq!(NamingConvention::classify("MyStruct"), NamingConvention::PascalCase);
        assert_eq!(NamingConvention::classify("UserService"), NamingConvention::PascalCase);
        assert_eq!(NamingConvention::classify("HttpClient"), NamingConvention::PascalCase);

        // SCREAMING_SNAKE_CASE
        assert_eq!(NamingConvention::classify("MY_CONSTANT"), NamingConvention::ScreamingSnakeCase);
        assert_eq!(NamingConvention::classify("MAX_SIZE"), NamingConvention::ScreamingSnakeCase);
        assert_eq!(NamingConvention::classify("DEFAULT_TIMEOUT"), NamingConvention::ScreamingSnakeCase);

        // Unknown/mixed
        assert_eq!(NamingConvention::classify("myUser_name"), NamingConvention::Unknown);
    }

    #[test]
    fn test_is_generated_file() {
        assert!(is_generated_file("// GENERATED CODE\nfn main() {}"));
        assert!(is_generated_file("# GENERATED FILE\nfunction test() {}"));
        assert!(!is_generated_file("fn main() {}"));
        assert!(!is_generated_file("let x = 5;"));
    }

    #[test]
    fn test_style_002_registered() {
        let rule = STYLE_002Rule::new();
        assert_eq!(rule.id(), "STYLE_002");
        assert!(rule.name().len() > 0);
        assert_eq!(rule.severity(), Severity::Minor);
        assert_eq!(rule.category(), Category::CodeSmell);
    }

    #[test]
    fn test_style_002_default_threshold() {
        let rule = STYLE_002Rule::new();
        assert_eq!(rule.threshold, 3);
    }

    #[test]
    fn test_style_002_custom_threshold() {
        let rule = STYLE_002Rule { threshold: 5, ..Default::default() };
        assert_eq!(rule.threshold, 5);
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // False Positive Guards (as per fixture matrix)
    // ═══════════════════════════════════════════════════════════════════════════

    #[test]
    fn test_fp_guard_constants() {
        // SCREAMING_SNAKE_CASE constants should not trigger
        let source = r#"
const MAX_SIZE = 100;
const DEFAULT_TIMEOUT = 30;
function getMaxSize() { }
"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        // Constants in UPPER_SNAKE_CASE are valid exception - no issue
        assert!(issues.is_empty(), "SCREAMING_SNAKE_CASE constants should not trigger");
    }

    #[test]
    fn test_fp_guard_generated_code() {
        // Generated code should be skipped
        let source = r#"
// GENERATED CODE - DO NOT EDIT
let user_id = 1;
let userId = 2;
"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(issues.is_empty(), "Generated code should be skipped");
    }

    #[test]
    fn test_fp_guard_insufficient_sample() {
        // Only 2 identifiers - insufficient sample
        let source = r#"let a = 1;
let b = 2;"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(issues.is_empty(), "Insufficient sample size should not trigger");
    }

    #[test]
    fn test_fp_guard_single_identifier() {
        // Only 1 identifier
        let source = r#"let x = 5;"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(issues.is_empty(), "Single identifier should not trigger");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Positive Cases (should trigger)
    // ═══════════════════════════════════════════════════════════════════════════

    #[test]
    fn test_positive_python_mixed() {
        // Python mixing snake_case and camelCase
        let source = "def get_user_id():\n    user_name = 'John'\n    userId = get_current_user()\n    return user_name\n";
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "python", &rule);
        assert!(!issues.is_empty(), "Python mixed conventions should trigger");
    }

    #[test]
    fn test_positive_javascript_mixed() {
        // JavaScript mixing snake_case and camelCase
        let source = "function get_user_id() {\n  let user_name = 'John';\n  let userId = 123;\n  return user_name;\n}\n";
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(!issues.is_empty(), "JavaScript mixed conventions should trigger");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Negative Cases (should NOT trigger)
    // ═══════════════════════════════════════════════════════════════════════════

    #[test]
    fn test_negative_python_consistent() {
        // Python with only snake_case
        let source = r#"
def get_user_id():
    user_name = 'John'
    return user_name
"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "python", &rule);
        assert!(issues.is_empty(), "Consistent snake_case should not trigger");
    }

    #[test]
    fn test_negative_javascript_consistent() {
        // JavaScript with only camelCase
        let source = r#"
function getUserId() {
  let userName = 'John';
  return userName;
}
"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(issues.is_empty(), "Consistent camelCase should not trigger");
    }

    #[test]
    fn test_negative_threshold_met_but_one_is_constant() {
        // Exactly 3 snake_case and 3 camelCase but constants are excluded
        let source = r#"
const MAX_SIZE = 100;
const DEFAULT_TIMEOUT = 30;
function getMaxSize() { }
"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(issues.is_empty(), "Constants should be excluded from analysis");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Edge Cases
    // ═══════════════════════════════════════════════════════════════════════════

    #[test]
    fn test_edge_empty_file() {
        let source = "";
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(issues.is_empty(), "Empty file should not trigger");
    }

    #[test]
    fn test_edge_exactly_threshold() {
        // Exactly 3 snake_case and 3 camelCase - threshold met
        let source = r#"
let user_id = 1;
let user_name = 2;
let created_at = 3;
let userId = 4;
let userName = 5;
let createdAt = 6;
"#;
        let rule = STYLE_002Rule::new();
        let issues = run_rule_check(source, "javascript", &rule);
        assert!(!issues.is_empty(), "Exactly threshold should trigger");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Helper function
    // ═══════════════════════════════════════════════════════════════════════════

    fn run_rule_check(source: &str, language: &str, rule: &STYLE_002Rule) -> Vec<Issue> {
        use cognicode_core::infrastructure::parser::Language;
        use cognicode_core::domain::aggregates::call_graph::CallGraph;
        use std::path::Path;
        use tree_sitter::Parser as TsParser;

        let lang = match language {
            "javascript" => Language::JavaScript,
            "typescript" => Language::TypeScript,
            "python" => Language::Python,
            _ => Language::JavaScript,
        };

        let ts_language = lang.to_ts_language();
        let mut parser = TsParser::new();
        parser.set_language(&ts_language).unwrap();
        let tree = parser.parse(source, None).unwrap();
        let graph = CallGraph::new();
        let metrics = crate::rules::FileMetrics::new();
        let symbol_table = crate::rules::symbol_table::SymbolTableBuilder::new()
            .build(&tree, source);

        let ctx = RuleContext {
            tree: &tree,
            source,
            file_path: Path::new("test.js"),
            language: &lang,
            graph: &graph,
            metrics: &metrics,
            symbol_table: Some(&symbol_table),
        };

        rule.check(&ctx)
    }
}