//! End-to-end integration test for the 6 `brain_*` MCP tools.
//!
//! Pins the public API surface (constants, helper functions) and
//! confirms the handler carries a fresh empty registry. The full
//! dispatch lifecycle is exercised in the unit tests at
//! `mcp::tests::brain_full_lifecycle_open_attach_focus_status_close`
//! which has direct access to the private `dispatch()` helper.
//!
//! Why split: the rmcp `RequestContext<RoleServer>` constructor is
//! `pub(crate)` inside the rmcp crate, so we cannot drive the
//! public `ServerHandler::call_tool` future from an external
//! integration test. The dispatch contract is therefore pinned by
//! the in-crate unit tests, and the public surface (constants,
//! handler construction, accessor methods) is pinned here.
//!
//! This integration test is gated behind the `test-utils` feature
//! so it can call the `ExplorerMcpHandler::registry()` accessor.

#![cfg(feature = "test-utils")]

use std::sync::Arc;

use cognicode_explorer::mcp::{
    ExplorerMcpHandler, TOOL_BRAIN_ASK, TOOL_BRAIN_ATTACH, TOOL_BRAIN_CLOSE, TOOL_BRAIN_FOCUS,
    TOOL_BRAIN_OPEN, TOOL_BRAIN_STATUS,
};

fn build_minimal_handler() -> Arc<ExplorerMcpHandler> {
    use cognicode_core::domain::aggregates::SymbolId;
    use cognicode_explorer::adapters::FsSourceReader;
    use cognicode_explorer::ports::symbol_repository::{
        GraphStats, RelationTarget, ResolvedSymbol, SymbolRepository,
    };
    use cognicode_explorer::service::ExplorerService;

    let dir = tempfile::tempdir().expect("tempdir");

    struct NoopRepo;
    impl SymbolRepository for NoopRepo {
        fn resolve(
            &self,
            _: &SymbolId,
        ) -> cognicode_explorer::ExplorerResult<Option<ResolvedSymbol>> {
            Ok(None)
        }
        fn callers(&self, _: &SymbolId) -> Vec<RelationTarget> {
            Vec::new()
        }
        fn callees(&self, _: &SymbolId) -> Vec<RelationTarget> {
            Vec::new()
        }
        fn fan_in(&self, _: &SymbolId) -> usize {
            0
        }
        fn fan_out(&self, _: &SymbolId) -> usize {
            0
        }
        fn find_symbols_by_name(
            &self,
            _: &str,
        ) -> cognicode_explorer::ExplorerResult<Vec<ResolvedSymbol>> {
            Ok(Vec::new())
        }
        fn find_symbols_by_file(
            &self,
            _: &str,
        ) -> cognicode_explorer::ExplorerResult<Vec<ResolvedSymbol>> {
            Ok(Vec::new())
        }
        fn module_list(&self) -> Vec<String> {
            Vec::new()
        }
        fn all_symbols(&self) -> cognicode_explorer::ExplorerResult<Vec<ResolvedSymbol>> {
            Ok(Vec::new())
        }
        fn graph_stats(&self) -> GraphStats {
            GraphStats {
                symbol_count: 0,
                relation_count: 0,
            }
        }
    }
    let repo: Arc<dyn SymbolRepository> = Arc::new(NoopRepo);
    let reader = Arc::new(FsSourceReader::new(dir.path().to_path_buf()));
    let service = Arc::new(ExplorerService::new(repo, reader, dir.path().to_path_buf()));
    Arc::new(ExplorerMcpHandler::new(service))
}

/// The 6 `brain_*` tool constants are part of the wire-level
/// contract. They MUST appear in `tool_names()` so downstream agent
/// harnesses that introspect the surface don't silently miss them.
#[test]
fn brain_session_tool_names_present_in_public_surface() {
    let names = cognicode_explorer::mcp::tool_names();
    for tool in [
        TOOL_BRAIN_OPEN,
        TOOL_BRAIN_ATTACH,
        TOOL_BRAIN_ASK,
        TOOL_BRAIN_FOCUS,
        TOOL_BRAIN_STATUS,
        TOOL_BRAIN_CLOSE,
    ] {
        assert!(
            names.contains(&tool),
            "tool_names() must include `{tool}` — got: {names:?}"
        );
    }
    // And the public count is 24 (18 prior + 6 brain_session).
    assert_eq!(names.len(), 24);
}

/// The handler carries a fresh empty registry at construction.
/// No stale sessions leak across handler instances.
#[test]
fn brain_session_handler_starts_with_empty_registry() {
    let handler = build_minimal_handler();
    assert_eq!(
        handler.registry().len(),
        0,
        "fresh handler must have an empty session registry"
    );
}

/// The session id generated by `brain_open` is a UUIDv4-shaped
/// 36-character string with the canonical 8-4-4-4-12 hex layout.
/// We pin the wire-level shape (NOT the underlying entropy source)
/// because that's what consumers depend on.
#[test]
fn brain_session_open_generates_uuid_v4_shaped_id() {
    use cognicode_explorer::session::SessionRegistry;
    let reg = SessionRegistry::new();
    let id_a = reg.open("ws".into(), 1800, handler_service(), None);
    let id_b = reg.open("ws".into(), 1800, handler_service(), None);
    // Shape.
    assert_eq!(id_a.len(), 36, "id must be 36 chars, got `{id_a}`");
    assert_eq!(id_a.chars().filter(|c| *c == '-').count(), 4);
    assert_eq!(id_a.chars().filter(|c| c.is_ascii_hexdigit()).count(), 32);
    // Uniqueness across two open calls (a 122-bit entropy source
    // means the probability of a collision in a test run is
    // effectively zero).
    assert_ne!(id_a, id_b, "session ids must be unique across opens");
}

fn handler_service() -> Arc<cognicode_explorer::service::ExplorerService> {
    use cognicode_core::domain::aggregates::SymbolId;
    use cognicode_explorer::adapters::FsSourceReader;
    use cognicode_explorer::ports::symbol_repository::{
        GraphStats, RelationTarget, ResolvedSymbol, SymbolRepository,
    };
    use cognicode_explorer::service::ExplorerService;

    let dir = tempfile::tempdir().expect("tempdir");
    struct NoopRepo;
    impl SymbolRepository for NoopRepo {
        fn resolve(
            &self,
            _: &SymbolId,
        ) -> cognicode_explorer::ExplorerResult<Option<ResolvedSymbol>> {
            Ok(None)
        }
        fn callers(&self, _: &SymbolId) -> Vec<RelationTarget> {
            Vec::new()
        }
        fn callees(&self, _: &SymbolId) -> Vec<RelationTarget> {
            Vec::new()
        }
        fn fan_in(&self, _: &SymbolId) -> usize {
            0
        }
        fn fan_out(&self, _: &SymbolId) -> usize {
            0
        }
        fn find_symbols_by_name(
            &self,
            _: &str,
        ) -> cognicode_explorer::ExplorerResult<Vec<ResolvedSymbol>> {
            Ok(Vec::new())
        }
        fn find_symbols_by_file(
            &self,
            _: &str,
        ) -> cognicode_explorer::ExplorerResult<Vec<ResolvedSymbol>> {
            Ok(Vec::new())
        }
        fn module_list(&self) -> Vec<String> {
            Vec::new()
        }
        fn all_symbols(&self) -> cognicode_explorer::ExplorerResult<Vec<ResolvedSymbol>> {
            Ok(Vec::new())
        }
        fn graph_stats(&self) -> GraphStats {
            GraphStats {
                symbol_count: 0,
                relation_count: 0,
            }
        }
    }
    let repo: Arc<dyn SymbolRepository> = Arc::new(NoopRepo);
    let reader = Arc::new(FsSourceReader::new(dir.path().to_path_buf()));
    Arc::new(ExplorerService::new(repo, reader, dir.path().to_path_buf()))
}
