/**
 * React hook for WASM-compiled graph algorithms.
 *
 * Lazy-loads the cognicode-graph-wasm module on first call to
 * pagerank() or godNodes(). The module is loaded exactly once per
 * browser session; subsequent calls reuse the same instance.
 *
 * Feature-gated: when VITE_ENABLE_WASM is not 'true', the hook returns
 * stub functions that throw a clear error directing callers to the
 * backend endpoint fallback. This lets feature-flagged environments
 * disable WASM entirely without breaking the build.
 *
 * WASM module location: apps/explorer-ui/src/wasm/cognicode_graph_wasm/
 *   generated by: wasm-pack build crates/cognicode-graph-wasm \
 *                    --target web --out-dir ../../apps/explorer-ui/src/wasm
 */

import { useCallback, useEffect, useRef, useState } from "react";
import type {
  AllSimplePathsOutput,
  ClusterComponentsOutput,
  CommunityGodNodesOutput,
  CommunitiesOutput,
  CondensationOutput,
  FeedbackArcSetOutput,
  SurprisingConnectionsOutput,
  TransitiveReductionOutput,
  WasmGodNodesOutput,
  WasmPageRankOutput,
} from "../api/types";

// Vite serves assets from /src/wasm/ at the same path. The wasm-pack
// --target web output produces a JS module that loads the .wasm binary.
// We dynamically import to keep it out of the initial bundle.
type WasmModule = {
  default: (input?: string | URL) => Promise<unknown>;
  pagerank: (nodes: unknown, edges: unknown, options: unknown) => WasmPageRankOutput;
  god_nodes: (nodes: unknown, edges: unknown, options: unknown) => WasmGodNodesOutput;
  communities: (nodes: unknown, edges: unknown, options: unknown) => CommunitiesOutput;
  community_god_nodes: (
    nodes: unknown,
    edges: unknown,
    communities: unknown,
    options: unknown
  ) => CommunityGodNodesOutput;
  surprising_connections: (
    nodes: unknown,
    edges: unknown,
    communities: unknown,
    options: unknown
  ) => SurprisingConnectionsOutput;
  condensation: (nodes: unknown, edges: unknown) => CondensationOutput;
  transitive_reduction: (nodes: unknown, edges: unknown) => TransitiveReductionOutput;
  feedback_arc_set: (nodes: unknown, edges: unknown) => FeedbackArcSetOutput;
  all_simple_paths: (
    nodes: unknown,
    edges: unknown,
    fromId: unknown,
    toId: unknown,
    options: unknown
  ) => AllSimplePathsOutput;
  cluster_components: (nodes: unknown, edges: unknown) => { clusters: string[][] };
};

type WasmState = "idle" | "loading" | "ready" | "error";

export interface UseGraphAlgorithmsResult {
  /**
   * PageRank scores keyed by node id.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param options - Optional { damping?: number, maxIterations?: number }.
   */
  pagerank: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    options?: { damping?: number; maxIterations?: number }
  ) => Promise<WasmPageRankOutput>;
  /**
   * God nodes sorted desc by score, ties broken by id ascending.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param options - Optional { percentile?: number } (default 0.95).
   */
  godNodes: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    options?: { percentile?: number }
  ) => Promise<WasmGodNodesOutput>;
  /**
   * Detect communities using Label Propagation.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param options - Optional { maxIterations?: number } (default 100).
   */
  communities: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    options?: { maxIterations?: number }
  ) => Promise<CommunitiesOutput>;
  /**
   * Find god nodes within each community.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param communities - Array of communities, each an array of node IDs.
   * @param options - Optional { percentile?: number } (default 0.95).
   */
  communityGodNodes: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    communities: string[][],
    options?: { percentile?: number }
  ) => Promise<CommunityGodNodesOutput>;
  /**
   * Find surprising cross-community connections.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param communities - Array of communities, each an array of node IDs.
   * @param options - Optional { limit?: number } (default 10).
   */
  surprisingConnections: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    communities: string[][],
    options?: { limit?: number }
  ) => Promise<SurprisingConnectionsOutput>;
  /**
   * Strongly connected components via Tarjan's algorithm.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   */
  condensation: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[]
  ) => Promise<CondensationOutput>;
  /**
   * Transitive reduction — minimal edge set preserving reachability.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   */
  transitiveReduction: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[]
  ) => Promise<TransitiveReductionOutput>;
  /**
   * Feedback arc set — edges whose removal breaks all cycles.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   */
  feedbackArcSet: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[]
  ) => Promise<FeedbackArcSetOutput>;
  /**
   * All simple paths between two nodes bounded by max_hops.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param fromId - Source node ID.
   * @param toId - Target node ID.
   * @param options - Optional { maxHops?: number } (default 10).
   */
  allSimplePaths: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    fromId: string,
    toId: string,
    options?: { maxHops?: number }
  ) => Promise<AllSimplePathsOutput>;
  /**
   * Cluster components — SCC + weakly connected components combined.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   */
  clusterComponents: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[]
  ) => Promise<ClusterComponentsOutput>;
  /** WASM module load state. */
  state: WasmState;
  /** Error if state === 'error'. */
  error: Error | null;
  /**
   * True if VITE_ENABLE_WASM === 'true' (i.e. WASM is enabled at build time).
   * When false, pagerank/godNodes/communities throw with a helpful error message.
   */
  enabled: boolean;
}

/**
 * Determine at module-load time whether WASM is enabled.
 *
 * Vite injects import.meta.env.VITE_ENABLE_WASM at build time.
 * Default false — WASM is opt-in per ADR-047 §2 (feature-gated opt-in).
 */
const WASM_ENABLED: boolean = import.meta.env.VITE_ENABLE_WASM === "true";

/**
 * Path to the wasm-pack generated JS entry point.
 * Vite serves files under /src/wasm/ from apps/explorer-ui/src/wasm/.
 *
 * Build command:
 *   wasm-pack build crates/cognicode-graph-wasm \
 *     --target web --out-dir ../../apps/explorer-ui/src/wasm
 */
const WASM_MODULE_URL =
  "/src/wasm/cognicode_graph_wasm/cognicode_graph_wasm.js";

export function useGraphAlgorithms(): UseGraphAlgorithmsResult {
  const moduleRef = useRef<WasmModule | null>(null);
  const loadPromiseRef = useRef<Promise<WasmModule> | null>(null);
  const [state, setState] = useState<WasmState>("idle");
  const [error, setError] = useState<Error | null>(null);

  const loadModule = useCallback(async (): Promise<WasmModule> => {
    if (moduleRef.current) return moduleRef.current;
    if (loadPromiseRef.current) return loadPromiseRef.current;

    setState("loading");
    const promise = (async () => {
      try {
        // Dynamic import — keeps WASM out of the initial bundle.
        // Vite handles .wasm imports via the vite-plugin-wasm plugin
        // configured in vite.config.ts.
        const mod = (await import(
          /* @vite-ignore */ WASM_MODULE_URL
        )) as WasmModule;
        // wasm-pack --target web output: the default export is an
        // initializer that returns a Promise. We don't need to await
        // it here because the function exports are bound to the
        // module instance directly (Vite serves the .wasm from
        // /src/wasm/... automatically when called).
        moduleRef.current = mod;
        setState("ready");
        return mod;
      } catch (e) {
        const err = e instanceof Error ? e : new Error(String(e));
        setError(err);
        setState("error");
        throw err;
      }
    })();

    loadPromiseRef.current = promise;
    return promise;
  }, []);

  // Pre-load on first mount (best-effort, doesn't block render).
  useEffect(() => {
    if (!WASM_ENABLED) return;
    loadModule().catch(() => {
      // Error already captured in state/error.
    });
  }, [loadModule]);

  const pagerankFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      options?: { damping?: number; maxIterations?: number }
    ): Promise<WasmPageRankOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM pagerank is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/pagerank instead."
        );
      }
      const mod = await loadModule();
      return mod.pagerank(nodes, edges, options ?? {});
    },
    [loadModule]
  );

  const godNodesFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      options?: { percentile?: number }
    ): Promise<WasmGodNodesOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM god_nodes is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/god-nodes instead."
        );
      }
      const mod = await loadModule();
      return mod.god_nodes(nodes, edges, options ?? {});
    },
    [loadModule]
  );

  const communitiesFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      options?: { maxIterations?: number }
    ): Promise<CommunitiesOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM communities is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/communities instead."
        );
      }
      const mod = await loadModule();
      return mod.communities(nodes, edges, options ?? {});
    },
    [loadModule]
  );

  const communityGodNodesFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      communities: string[][],
      options?: { percentile?: number }
    ): Promise<CommunityGodNodesOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM community_god_nodes is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/community-god-nodes instead."
        );
      }
      const mod = await loadModule();
      return mod.community_god_nodes(nodes, edges, communities, options ?? {});
    },
    [loadModule]
  );

  const surprisingConnectionsFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      communities: string[][],
      options?: { limit?: number }
    ): Promise<SurprisingConnectionsOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM surprising_connections is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/surprising-connections instead."
        );
      }
      const mod = await loadModule();
      return mod.surprising_connections(nodes, edges, communities, options ?? {});
    },
    [loadModule]
  );

  const condensationFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[]
    ): Promise<CondensationOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM condensation is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/condensation instead."
        );
      }
      const mod = await loadModule();
      return mod.condensation(nodes, edges);
    },
    [loadModule]
  );

  const transitiveReductionFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[]
    ): Promise<TransitiveReductionOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM transitive_reduction is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/transitive-reduction instead."
        );
      }
      const mod = await loadModule();
      return mod.transitive_reduction(nodes, edges);
    },
    [loadModule]
  );

  const feedbackArcSetFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[]
    ): Promise<FeedbackArcSetOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM feedback_arc_set is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/feedback-arc-set instead."
        );
      }
      const mod = await loadModule();
      return mod.feedback_arc_set(nodes, edges);
    },
    [loadModule]
  );

  const allSimplePathsFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      fromId: string,
      toId: string,
      options?: { maxHops?: number }
    ): Promise<AllSimplePathsOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM all_simple_paths is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/all-simple-paths instead."
        );
      }
      const mod = await loadModule();
      return mod.all_simple_paths(nodes, edges, fromId, toId, options ?? {});
    },
    [loadModule]
  );

  const clusterComponentsFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[]
    ): Promise<ClusterComponentsOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM cluster_components is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/cluster-components instead."
        );
      }
      const mod = await loadModule();
      return mod.cluster_components(nodes, edges);
    },
    [loadModule]
  );

  return {
    pagerank: pagerankFn,
    godNodes: godNodesFn,
    communities: communitiesFn,
    communityGodNodes: communityGodNodesFn,
    surprisingConnections: surprisingConnectionsFn,
    condensation: condensationFn,
    transitiveReduction: transitiveReductionFn,
    feedbackArcSet: feedbackArcSetFn,
    allSimplePaths: allSimplePathsFn,
    clusterComponents: clusterComponentsFn,
    state,
    error,
    enabled: WASM_ENABLED,
  };
}
