/**
 * React hook for WASM-compiled graph algorithms.
 *
 * Lazy-loads the cognicode-graph-wasm module on first call to
 * pagerank() or godNodes(). The module is loaded exactly once per
 * browser session; subsequent calls reuse the same instance.
 *
 * Feature-gated: when VITE_ENABLE_WASM is not 'true', the hook returns
 * stub functions that throw a clear error directing callers to the
 * backend endpoint fallback. This lets feature-flagged environments
 * disable WASM entirely without breaking the build.
 *
 * WASM module location: apps/explorer-ui/src/wasm/cognicode_graph_wasm/
 *   generated by: wasm-pack build crates/cognicode-graph-wasm \
 *                    --target web --out-dir ../../apps/explorer-ui/src/wasm
 */

import { useCallback, useEffect, useRef, useState } from "react";
import type {
  WasmGodNodesOutput,
  WasmPageRankOutput,
} from "../api/types";

// Vite serves assets from /src/wasm/ at the same path. The wasm-pack
// --target web output produces a JS module that loads the .wasm binary.
// We dynamically import to keep it out of the initial bundle.
type WasmModule = {
  default: (input?: string | URL) => Promise<unknown>;
  pagerank: (nodes: unknown, edges: unknown, options: unknown) => WasmPageRankOutput;
  god_nodes: (nodes: unknown, edges: unknown, options: unknown) => WasmGodNodesOutput;
};

type WasmState = "idle" | "loading" | "ready" | "error";

export interface UseGraphAlgorithmsResult {
  /**
   * PageRank scores keyed by node id.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param options - Optional { damping?: number, maxIterations?: number }.
   */
  pagerank: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    options?: { damping?: number; maxIterations?: number }
  ) => Promise<WasmPageRankOutput>;
  /**
   * God nodes sorted desc by score, ties broken by id ascending.
   *
   * @param nodes - Array of { id, label? } objects representing graph nodes.
   * @param edges - Array of { source, target } objects representing directed edges.
   * @param options - Optional { percentile?: number } (default 0.95).
   */
  godNodes: (
    nodes: { id: string; label?: string | null }[],
    edges: { source: string; target: string }[],
    options?: { percentile?: number }
  ) => Promise<WasmGodNodesOutput>;
  /** WASM module load state. */
  state: WasmState;
  /** Error if state === 'error'. */
  error: Error | null;
  /**
   * True if VITE_ENABLE_WASM === 'true' (i.e. WASM is enabled at build time).
   * When false, pagerank/godNodes throw with a helpful error message.
   */
  enabled: boolean;
}

/**
 * Determine at module-load time whether WASM is enabled.
 *
 * Vite injects import.meta.env.VITE_ENABLE_WASM at build time.
 * Default false — WASM is opt-in per ADR-047 §2 (feature-gated opt-in).
 */
const WASM_ENABLED: boolean = import.meta.env.VITE_ENABLE_WASM === "true";

/**
 * Path to the wasm-pack generated JS entry point.
 * Vite serves files under /src/wasm/ from apps/explorer-ui/src/wasm/.
 *
 * Build command:
 *   wasm-pack build crates/cognicode-graph-wasm \
 *     --target web --out-dir ../../apps/explorer-ui/src/wasm
 */
const WASM_MODULE_URL =
  "/src/wasm/cognicode_graph_wasm/cognicode_graph_wasm.js";

export function useGraphAlgorithms(): UseGraphAlgorithmsResult {
  const moduleRef = useRef<WasmModule | null>(null);
  const loadPromiseRef = useRef<Promise<WasmModule> | null>(null);
  const [state, setState] = useState<WasmState>("idle");
  const [error, setError] = useState<Error | null>(null);

  const loadModule = useCallback(async (): Promise<WasmModule> => {
    if (moduleRef.current) return moduleRef.current;
    if (loadPromiseRef.current) return loadPromiseRef.current;

    setState("loading");
    const promise = (async () => {
      try {
        // Dynamic import — keeps WASM out of the initial bundle.
        // Vite handles .wasm imports via the vite-plugin-wasm plugin
        // configured in vite.config.ts.
        const mod = (await import(
          /* @vite-ignore */ WASM_MODULE_URL
        )) as WasmModule;
        // wasm-pack --target web output: the default export is an
        // initializer that returns a Promise. We don't need to await
        // it here because the function exports are bound to the
        // module instance directly (Vite serves the .wasm from
        // /src/wasm/... automatically when called).
        moduleRef.current = mod;
        setState("ready");
        return mod;
      } catch (e) {
        const err = e instanceof Error ? e : new Error(String(e));
        setError(err);
        setState("error");
        throw err;
      }
    })();

    loadPromiseRef.current = promise;
    return promise;
  }, []);

  // Pre-load on first mount (best-effort, doesn't block render).
  useEffect(() => {
    if (!WASM_ENABLED) return;
    loadModule().catch(() => {
      // Error already captured in state/error.
    });
  }, [loadModule]);

  const pagerankFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      options?: { damping?: number; maxIterations?: number }
    ): Promise<WasmPageRankOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM pagerank is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/pagerank instead."
        );
      }
      const mod = await loadModule();
      return mod.pagerank(nodes, edges, options ?? {});
    },
    [loadModule]
  );

  const godNodesFn = useCallback(
    async (
      nodes: { id: string; label?: string | null }[],
      edges: { source: string; target: string }[],
      options?: { percentile?: number }
    ): Promise<WasmGodNodesOutput> => {
      if (!WASM_ENABLED) {
        throw new Error(
          "WASM god_nodes is disabled (VITE_ENABLE_WASM!==true). " +
            "Use the backend endpoint /api/graph/:id/god-nodes instead."
        );
      }
      const mod = await loadModule();
      return mod.god_nodes(nodes, edges, options ?? {});
    },
    [loadModule]
  );

  return {
    pagerank: pagerankFn,
    godNodes: godNodesFn,
    state,
    error,
    enabled: WASM_ENABLED,
  };
}
