#!/usr/bin/env python3
"""Auto-generate rule registry from rules/ directory.

Scans rules/{lang}/{category}/ and generates:
  - rules/rules/mod.rs (module declarations)
  - rules/registry.rs (re-exports for inventory::submit)
"""

import os
import re
from pathlib import Path
from typing import List, Tuple


RULES_ROOT = Path("crates/cognicode-axiom/src/rules")
RULES_DIR = RULES_ROOT / "rules"


def find_rule_files() -> List[Tuple[str, Path]]:
    """Find all rule files in rules/ directory.
    
    Returns list of (module_path, file_path).
    """
    rule_files = []
    
    if not RULES_DIR.exists():
        print(f"Rules directory not found: {RULES_DIR}")
        return rule_files
    
    for root, dirs, files in os.walk(RULES_DIR):
        for f in sorted(files):
            if f.endswith(".rs") and f != "mod.rs":
                filepath = Path(root) / f
                rel = filepath.relative_to(RULES_ROOT)
                module_path = str(rel.with_suffix("")).replace("/", "::")
                rule_files.append((module_path, filepath))
    
    return rule_files


def extract_struct_name(filepath: Path) -> str:
    """Extract the rule struct name from a rule file.
    
    Looks for: pub struct S134Rule or declare_rule! { id: "S134" ... }
    """
    content = filepath.read_text()
    
    # Try to find declare_rule! id
    id_match = re.search(r'id:\s*"([^"]+)"', content)
    if id_match:
        rule_id = id_match.group(1)
        return f"{rule_id}Rule"
    
    # Try to find pub struct XxxRule
    struct_match = re.search(r'pub\s+struct\s+(\w+Rule)', content)
    if struct_match:
        return struct_match.group(1)
    
    return None


def generate_mod_files(rule_files: List[Tuple[str, Path]]):
    """Generate mod.rs files for each directory level."""
    dir_modules = {}
    
    for module_path, filepath in rule_files:
        parts = module_path.split("::")
        file_stem = Path(filepath).stem
        
        # Group by directory
        for depth in range(len(parts)):
            dir_key = "::".join(parts[:depth])
            if dir_key not in dir_modules:
                dir_modules[dir_key] = set()
            if depth == len(parts) - 1:
                dir_modules[dir_key].add(file_stem)
    
    # Generate mod.rs for each directory
    for dir_key, modules in sorted(dir_modules.items()):
        if not modules:
            continue
        
        dir_path = RULES_ROOT / dir_key.replace("::", "/")
        dir_path.mkdir(parents=True, exist_ok=True)
        
        mod_content = "//! Auto-generated module declarations.\n\n"
        for mod_name in sorted(modules):
            mod_content += f"pub mod {mod_name};\n"
        
        mod_file = dir_path / "mod.rs"
        mod_file.write_text(mod_content)
        print(f"  Generated: {mod_file.relative_to(RULES_ROOT.parent)}")


def generate_registry(rule_files: List[Tuple[str, Path]]):
    """Generate registry.rs with all rule re-exports."""
    lines = [
        "//! Auto-generated rule registry. DO NOT EDIT MANUALLY.",
        "//!",
        f"//! Generated by: autoresearch/tools/generate_registry.py",
        f"//! Rules found: {len(rule_files)}",
        "",
        "use inventory::submit;",
        "",
        "// Re-export all rule modules",
    ]
    
    for module_path, _ in sorted(rule_files):
        lines.append(f"pub use crate::rules::rules::{module_path};")
    
    lines.append("")
    lines.append("// Individual rule struct re-exports")
    
    for module_path, filepath in sorted(rule_files):
        struct_name = extract_struct_name(filepath)
        if struct_name:
            lines.append(f"pub use crate::rules::rules::{module_path}::{struct_name};")
    
    registry_file = RULES_ROOT / "registry.rs"
    registry_file.write_text("\n".join(lines) + "\n")
    print(f"  Generated: {registry_file.relative_to(RULES_ROOT.parent)}")
    print(f"  Total rules: {len(rule_files)}")


def main():
    print("Generating rule registry...")
    
    rule_files = find_rule_files()
    if not rule_files:
        print("  No rule files found in rules/ directory.")
        print("  This is expected if rules haven't been segregated yet.")
        print("  The registry will be minimal.")
    
    generate_mod_files(rule_files)
    generate_registry(rule_files)
    
    print("Done.")


if __name__ == "__main__":
    main()
