#!/usr/bin/env python3
"""validate_skills.py — static validation for CogniCode skill bundles.

Implements the rules from WU17 of e84.1-cognicode-skill-productization:

  * User skills (skills/<name>/SKILL.md where name != cognicode-developer)
    MUST NOT contain:
      - /var/home/rubentxu
      - target/debug/
      - target/release/
      - any absolute path under /home/, /Users/, /var/, /opt/
      - references to internal-only docs (docs/ROADMAP.md, openspec/, docs/adr/)
      - just recipes (post-e31-audit, ci-t6, scorecard-nightly, scorecard-streak)
      - hard-coded version "0.92.0"

  * All skills MUST have valid frontmatter with:
      - name (matches directory name)
      - description (non-empty)
      - license

  * cognicode-mcp references tool names; verify each one exists in
    the published tool catalog (product/tools.json).

  * manifest.yaml MUST be valid YAML and parse cleanly.

Exit codes:
  0 = all validations passed
  1 = one or more skills failed validation
  2 = harness error (catalog missing, IO error)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"

# The published tool catalog, and the only one this gate resolves against.
#
# It used to be the newest `runtime-tools-list.json` under
# `openspec/changes/archive/`, which is a frozen historical record of one
# cycle's runtime capture. That made the gate's authority a function of
# which cycles happen to be archived: append a new archive with a
# different catalog and the skill gate silently starts validating against
# different tool names. It also left two sources of truth — the
# `cognicode.tools/v1` document the repo publishes (generated by
# `scripts/product/generate_tool_catalog.py` from a live runtime capture
# and gated by A-010/A-011) and an archived capture that nothing
# regenerates. Measured 2026-10-02: the two happened to agree, 73 names
# in both, so the divergence was latent rather than active. It is the
# same shape as the `EvidenceStore` lesson: resolve against the
# published authority so the two cannot drift apart unnoticed.
PUBLISHED_CATALOG = REPO_ROOT / "product/tools.json"

# The published profile document, for the same reason: a profile id is
# a legitimate backticked identifier that the runtime does not expose
# as a tool, and the set of them is published rather than hardcoded.
PUBLISHED_PROFILES = REPO_ROOT / "product/profiles.json"

# Patterns that MUST NOT appear in user-facing skills
USER_SKILL_FORBIDDEN_PATTERNS = [
    # Local-machine absolute paths
    (r"/var/home/rubentxu", "local-machine path /var/home/rubentxu"),
    (r"/home/rubentxu/Proyectos", "local-machine path /home/rubentxu/Proyectos"),
    (r"~/(Proyectos|proyectos)/rust/CogniCode", "local-machine path ~/Proyectos/..."),
    # Build paths
    (r"target/debug/", "Cargo target/debug path"),
    (r"target/release/", "Cargo target/release path"),
    # Internal-only docs
    (r"docs/ROADMAP\.md", "internal-only docs/ROADMAP.md"),
    (r"openspec/changes/", "internal-only openspec/changes/"),
    (r"openspec/CHANGES\.md", "internal-only openspec/CHANGES.md"),
    (r"docs/adr/", "internal-only docs/adr/"),
    # just recipes from the CogniCode repo
    (r"\bpost-e31-audit\b", "internal just recipe post-e31-audit"),
    (r"\bci-t6\b", "internal just recipe ci-t6"),
    (r"\bscorecard-nightly\b", "internal just recipe scorecard-nightly"),
    (r"\bscorecard-streak\b", "internal just recipe scorecard-streak"),
    # Stale version
    (r"\b0\.92\.\d+\b", "stale CogniCode version 0.92.x (current is 0.95.x)"),
    # Absolute system paths in examples
    (r"cd\s+/home/", "absolute path /home/"),
    (r"cd\s+/Users/", "absolute path /Users/"),
    (r"cd\s+/var/", "absolute path /var/"),
    (r"cd\s+/opt/", "absolute path /opt/"),
]

# Developer skills are allowed to contain internal references.
DEVELOPER_SKILL_ALLOWED_PATTERNS = [
    r"docs/ROADMAP\.md",
    r"docs/adr/",
    r"openspec/",
    r"post-e31-audit",
    r"just ",
    r"cd .*CogniCode",
]

# Frontmatter required fields
REQUIRED_FRONTMATTER = ["name", "description", "license"]


def read_skill(skill_dir: Path) -> tuple[str, str, str]:
    """Return (skill_md, manifest_yaml, skill_name)."""
    skill_md_path = skill_dir / "SKILL.md"
    if not skill_md_path.exists():
        raise FileNotFoundError(f"SKILL.md missing in {skill_dir}")
    skill_md = skill_md_path.read_text()

    manifest_path = skill_dir / "manifest.yaml"
    manifest_yaml = manifest_path.read_text() if manifest_path.exists() else ""

    skill_name = skill_dir.name
    return skill_md, manifest_yaml, skill_name


def parse_frontmatter(skill_md: str) -> dict[str, str]:
    """Extract YAML frontmatter between --- markers.

    Returns a dict of frontmatter fields. Uses a tiny parser to avoid
    requiring PyYAML for the simple `name: x` / `description: ...`
    shape used in our skills.
    """
    if not skill_md.startswith("---\n"):
        return {}
    end = skill_md.find("\n---", 4)
    if end == -1:
        return {}
    block = skill_md[4:end]

    out: dict[str, str] = {}
    current_key: str | None = None
    current_value_lines: list[str] = []
    for raw in block.splitlines():
        # Detect a new key
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", raw)
        if m:
            if current_key is not None:
                out[current_key] = "\n".join(current_value_lines).strip()
            current_key = m.group(1)
            tail = m.group(2)
            current_value_lines = [tail] if tail else []
        else:
            if current_key is not None:
                current_value_lines.append(raw)
    if current_key is not None:
        out[current_key] = "\n".join(current_value_lines).strip()
    return out


def validate_frontmatter(fm: dict[str, str], skill_name: str) -> list[str]:
    errors: list[str] = []
    for f in REQUIRED_FRONTMATTER:
        if f not in fm or not fm[f].strip():
            errors.append(f"frontmatter missing or empty field: {f}")
    if fm.get("name") and fm["name"] != skill_name:
        errors.append(
            f"frontmatter name '{fm['name']}' does not match directory '{skill_name}'"
        )
    return errors


def validate_user_skill(skill_md: str, skill_name: str) -> list[str]:
    errors: list[str] = []
    for pattern, desc in USER_SKILL_FORBIDDEN_PATTERNS:
        m = re.search(pattern, skill_md)
        if m:
            errors.append(
                f"{skill_name}: forbidden {desc} (matched: '{m.group(0)}')"
            )
    return errors


def validate_developer_skill(skill_md: str, skill_name: str) -> list[str]:
    # Developer skills have fewer restrictions. We still check for
    # target/debug paths (developer might still want to use cargo
    # build artifacts, but the skill should not enshrine them).
    errors: list[str] = []
    for pattern, desc in USER_SKILL_FORBIDDEN_PATTERNS:
        if "stale CogniCode version" in desc:
            continue  # developer skills may reference historical versions
        if "local-machine" in desc or "Cargo target" in desc:
            # developers ARE local to the repo, but should use repo-relative paths
            m = re.search(pattern, skill_md)
            if m:
                errors.append(
                    f"{skill_name}: developer skill should not hard-code "
                    f"{desc} (matched: '{m.group(0)}')"
                )
    return errors


# Backticked words that are not MCP tools. Everything here is a name a
# skill legitimately needs to write in backticks but that the runtime
# does not expose as a tool.
#
# This list is a denylist, and a denylist only knows what someone
# remembered to put in it. The published profile ids used to be absent
# from it and survived only because the skills happened to write them
# comma-separated, which trips the "near a parenthesis or comma means
# it is a parameter" heuristic further down. Rewording a profile list
# without commas turned three legitimate identifiers into
# "referenced MCP tool `reviewer` not in runtime catalog". The profile
# ids are not on this list because they are not hardcoded: they are
# derived from `product/profiles.json` at run time, which is the
# published authority (A-006) and the only place that can know what a
# profile is called.
NON_TOOL_NAMES = frozenset(
    {
        # binary names
        "cogh",
        "cognicode",
        "cognicode-mcp",
        # cogh subcommands (CLI, not MCP)
        "install",
        "uninstall",
        "list",
        "current",
        "latest",
        "update",
        "reshim",
        "rollback",
        "doctor",
        "where",
        "init",
        "plugin",
        "skill",
        "ide",
        "version",
        # cognicode subcommands (CLI, not MCP)
        "analyze",
        "serve",
        "refactor",
        "index",
        "graph",
        "navigate",
        # crates / external dependencies
        "tokio",
        "sqlx",
        "serde",
        "anyhow",
        "thiserror",
        # MCP plumbing
        "tools/list",
        "tools/call",
        # just recipes
        "build_release",
        "build_wasm",
        "build_server",
        "test_unit",
        "test_pg",
        "check_known_failures",
        "lint",
        "dev",
        "run",
        "start",
    }
)


def extract_tool_name_refs(
    skill_md: str, extra_non_tools: frozenset[str] = frozenset()
) -> set[str]:
    """Find MCP tool names referenced in the skill text.

    Looks for words in backticks that match MCP tool naming
    conventions (snake_case, lowercase), minus the names in
    `NON_TOOL_NAMES` and minus `extra_non_tools` — the published
    profile ids, which are legitimate backticked identifiers that the
    runtime does not expose as tools.

    `extra_non_tools` is a parameter rather than a module global so
    that "does the gate ignore profile names" is a question this
    function can be asked directly, with a synthetic set, instead of
    one that can only be answered by whatever the repo currently
    publishes.
    """
    refs: set[str] = set()
    for m in re.finditer(r"`([a-z][a-z0-9_]+)`", skill_md):
        name = m.group(1)
        # Filter out common non-tool names that appear in backticks
        if name in NON_TOOL_NAMES or name in extra_non_tools:
            continue
        # just recipes
        if name.startswith("just_"):
            continue
        if len(name) < 5:  # too short to be a real tool name
            continue
        refs.add(name)
    return refs


def validate_tool_refs(
    skill_md: str,
    skill_name: str,
    catalog: set[str],
    extra_non_tools: frozenset[str] = frozenset(),
) -> tuple[list[str], set[str]]:
    """Returns (errors, valid_refs).

    A reference is "valid" iff it is in the runtime catalog. Tokens
    that look like tool names but are not in the catalog are
    distinguished as follows:

    - Names in `extra_non_tools` (the published profile ids) are not
      tool references at all and are ignored here.
    - If the token appears within 20 characters of a `(` (likely a
      function/parameter list), it is treated as a parameter name
      and not flagged.
    - Otherwise it is flagged as a missing MCP tool reference.
    """
    refs = extract_tool_name_refs(skill_md, extra_non_tools)
    errors: list[str] = []
    valid_refs: set[str] = set()
    for r in refs:
        if r in catalog:
            valid_refs.add(r)
            continue
        # Heuristic: if the token is near `(`, treat as parameter.
        # Find every occurrence and check the chars immediately before.
        is_parameter = False
        for m in re.finditer(re.escape(r), skill_md):
            start = m.start()
            # Look back 20 chars for `(` or `,` or whitespace+`(`.
            preceding = skill_md[max(0, start - 20):start]
            if "(" in preceding or "," in preceding:
                is_parameter = True
                break
        if is_parameter:
            # Treat as parameter name, not missing tool.
            continue
        errors.append(
            f"{skill_name}: referenced MCP tool `{r}` not in runtime catalog"
        )
    return errors, valid_refs


def load_catalog() -> set[str] | None:
    """Tool names from the published catalog, or None if it is unavailable.

    `product/tools.json` is the published authority for the tool surface:
    it is generated from a live runtime capture by
    `scripts/product/generate_tool_catalog.py` and gated by A-010 (the
    catalog matches the authority the runtime enforces) and A-011 (every
    published document matches its schema).

    Returns None rather than an empty set when the catalog is missing,
    because the two are not interchangeable. An empty set is a claim —
    "this server exposes no tools" — and answering with it made the gate
    fail with one `not in runtime catalog` error per tool reference in
    every skill, while printing a warning that said the opposite:

        WARNING: runtime catalog not found at ...; tool-ref validation
        skipped.

    Nothing was skipped. Measured 2026-10-02 with the catalog absent:
    12 spurious errors across `cognicode-mcp` and
    `cognicode-agent-hardness`, all of them naming tools that exist. A
    warning that describes the opposite of what the code does is worse
    than no warning, because it tells the reader the gate is off when
    the gate is in fact misfiring. The caller turns None into exit 2, a
    harness error that says the gate could not run — the same shape as
    a missing `skills/` directory.
    """
    if not PUBLISHED_CATALOG.exists():
        return None
    data = json.loads(PUBLISHED_CATALOG.read_text())
    # `product/tools.json` is a document with a `tools` array; the
    # archived runtime capture it replaces was a bare list. Accept both
    # so the shape difference between the two eras is explicit here
    # rather than a latent AttributeError in a CI job.
    tools = data["tools"] if isinstance(data, dict) else data
    return {tool["name"] for tool in tools}


def load_profile_ids() -> frozenset[str] | None:
    """Profile ids from the published profiles document, or None if absent.

    `product/profiles.json` is the public source of truth for the
    profile set — A-006 moved it there to replace a hardcoded constant
    in the manifest, and `generate_profiles.py` now derives it from the
    Rust source rather than duplicating it. Reading it here is what
    keeps the skill gate from inventing a second, stale list of profile
    names.

    Returns None rather than an empty frozenset for the same reason
    `load_catalog` does: an empty set would mean "the product publishes
    no profiles", which is a claim, and answering with it would put
    every backticked profile name back into circulation as a
    suspected tool reference.
    """
    if not PUBLISHED_PROFILES.exists():
        return None
    data = json.loads(PUBLISHED_PROFILES.read_text())
    return frozenset(profile["id"] for profile in data["profiles"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skill",
        default=None,
        help="validate only this skill directory name (default: all)",
    )
    args = parser.parse_args()

    if not SKILLS_DIR.exists():
        print(f"ERROR: skills directory not found at {SKILLS_DIR}", file=sys.stderr)
        return 2

    catalog = load_catalog()
    if catalog is None:
        print(
            f"ERROR: published tool catalog not found at {PUBLISHED_CATALOG}; "
            "the skill tool-reference gate could not run. This is a harness "
            "error, not a pass: without it every tool reference below is "
            "checked against an empty catalog.",
            file=sys.stderr,
        )
        return 2

    profile_ids = load_profile_ids()
    if profile_ids is None:
        print(
            f"ERROR: published profiles not found at {PUBLISHED_PROFILES}; "
            "the skill tool-reference gate could not tell a profile name "
            "apart from a tool name. This is a harness error, not a pass: "
            "without it every backticked profile name is reported as a "
            "missing MCP tool.",
            file=sys.stderr,
        )
        return 2

    skill_dirs = sorted(
        d
        for d in SKILLS_DIR.iterdir()
        if d.is_dir()
        and not d.name.startswith(".")
        and (args.skill is None or d.name == args.skill)
    )

    if not skill_dirs:
        print(f"ERROR: no skills found in {SKILLS_DIR}", file=sys.stderr)
        return 2

    total_errors = 0
    for skill_dir in skill_dirs:
        skill_name = skill_dir.name
        print(f"== {skill_name} ==")

        # SkillSet (e.g. cognicode-recommended) has SET.yaml, not SKILL.md.
        set_yaml = skill_dir / "SET.yaml"
        if set_yaml.exists():
            try:
                import yaml
                data = yaml.safe_load(set_yaml.read_text())
                if data.get("kind") != "SkillSet":
                    print(f"  FAIL: SET.yaml kind must be 'SkillSet', got {data.get('kind')}")
                    total_errors += 1
                else:
                    print(f"  ok: SkillSet manifest valid")
            except ImportError:
                print(f"  SKIP: PyYAML not installed; cannot parse SET.yaml")
            except Exception as e:
                print(f"  FAIL: SET.yaml invalid YAML: {e}")
                total_errors += 1
            print()
            continue

        try:
            skill_md, manifest_yaml, name = read_skill(skill_dir)
        except FileNotFoundError as e:
            print(f"  FAIL: {e}")
            total_errors += 1
            continue

        # Frontmatter
        fm = parse_frontmatter(skill_md)
        if not fm:
            print(f"  FAIL: no frontmatter found")
            total_errors += 1
            continue
        for e in validate_frontmatter(fm, skill_name):
            print(f"  FAIL: {e}")
            total_errors += 1

        # Manifest YAML (basic syntax)
        if not manifest_yaml:
            print(f"  FAIL: manifest.yaml missing")
            total_errors += 1
        else:
            try:
                import yaml
                yaml.safe_load(manifest_yaml)
            except ImportError:
                pass  # PyYAML not installed; skip detailed check
            except Exception as e:
                print(f"  FAIL: manifest.yaml invalid YAML: {e}")
                total_errors += 1

        # Skill-specific rules
        if skill_name == "cognicode-developer":
            for e in validate_developer_skill(skill_md, skill_name):
                print(f"  FAIL: {e}")
                total_errors += 1
        else:
            for e in validate_user_skill(skill_md, skill_name):
                print(f"  FAIL: {e}")
                total_errors += 1

        # Tool references. Every skill that talks about MCP has its
        # backticked tool names checked against the published catalog.
        #
        # The guard used to be `catalog and "MCP" in skill_md or "mcp" in
        # skill_md.lower()`. `and` binds tighter than `or`, so it parsed
        # as `(catalog and "MCP" in skill_md) or ("mcp" in skill_md.lower())`
        # — and `"MCP" in skill_md` implies `"mcp" in skill_md.lower()`, so
        # the first disjunct was subsumed and the `catalog` half of it was
        # the only part doing anything. With the catalog missing, the second
        # disjunct still let the branch run, which is how a supposedly
        # skipped check produced 12 errors. The catalog is now guaranteed
        # non-empty-or-exit-2 above, so the guard is only the question it
        # was always meant to ask.
        if "mcp" in skill_md.lower():
            errs, valid = validate_tool_refs(
                skill_md, skill_name, catalog, profile_ids
            )
            for e in errs:
                print(f"  FAIL: {e}")
                total_errors += 1
            if valid:
                print(f"  ok: {len(valid)} MCP tool reference(s) validated")

    print()
    if total_errors == 0:
        print(f"PASS: all {len(skill_dirs)} skill(s) validated")
        return 0
    else:
        print(f"FAIL: {total_errors} validation error(s)")
        return 1


if __name__ == "__main__":
    sys.exit(main())
