//! S819 — Source files should not be too long
//!
//! Detects files that exceed a configurable line count threshold.
//! This is a metrics-based rule that does not require AST traversal.
//!
//! ## False Positives
//! - Generated files (markers like "// GENERATED", "# GENERATED", etc.)
//! - Test files (may legitimately have many test cases)
//! - Proto-generated files
//!
//! ## Configuration
//! - `threshold`: Maximum allowed lines (default: 500)
use crate::{Severity, Category, Issue, Remediation, Rule, RuleContext, RuleEntry};
use crate::rules::{CleanCodeAttribute, SoftwareQuality, SoftwareQualityImpact, ImpactSeverity};
use cognicode_macros::declare_rule;
use inventory::submit;

/// Markers that indicate a file is generated and should be skipped
const GENERATED_MARKERS: &[&str] = &[
    "// GENERATED",
    "# GENERATED",
    "/* GENERATED",
    "// This file is generated",
    "# This file is generated",
    "// Automatically generated",
    "# Automatically generated",
    "// Code generated by",
    "# Code generated by",
    "@generated",
];

/// File name patterns that indicate generated content
const GENERATED_NAME_PATTERNS: &[&str] = &[
    ".pb.rs",    // protobuf generated
    ".pb.swift", // protobuf generated
    "_pb2.py",   // protobuf generated Python
    ".g.rs",     // tonic/gRPC generated
    "_generated",
    "_gen.",
];

declare_rule! {
    id: "S819"
    name: "Source files should not be too long"
    severity: Major
    category: CodeSmell
    language: "*"
    params: {
        threshold: usize = 500,
        test_threshold: usize = 800
    }

    explanation: "Source files that are too long are difficult to maintain, understand, and review. Large files often indicate a need for refactoring into smaller, focused modules or components. The default threshold is 500 lines, but test files get a higher limit of 800 lines to account for legitimate test case accumulations.",
    clean_code: Focused,
    impacts: [Maintainability: Medium],
    auto_test: true

    agent_semantics: {
        summary: "Files exceeding {threshold} lines are difficult to maintain",
        fix_playbook: "1. Identify cohesive groups of functionality\n2. Extract each group into a separate module\n3. Use the module system to organize code\n4. Keep shared utilities in a common module",
        review_questions: [
            "Is this file doing multiple things?",
            "Can it be split by responsibility?",
            "Are there natural division points?",
            "What imports are shared across sections?"
        ],
        semantic_chunks: ["maintainability", "file-length", "refactoring", "modularity"],
        safe_autofix: false,
        autofix_guidance: "Split file into modules by responsibility — requires human review for correct module boundaries"
    }

    check: => {
        let mut issues = Vec::new();
        let source = ctx.source;
        let file_path = ctx.file_path;
        let file_name = file_path.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("");

        // Skip if file appears to be generated
        if is_generated_file(source, file_name) {
            return issues;
        }

        // Count lines (excluding trailing newline)
        let line_count = source.lines().count();

        // Determine threshold based on file type
        let threshold = if is_test_file(file_name) {
            self.test_threshold
        } else {
            self.threshold
        };

        if line_count > threshold {
            let file_type_desc = if is_test_file(file_name) {
                "test file"
            } else {
                "source file"
            };

            issues.push(Issue::new(
                "S819",
                format!(
                    "File '{}' has {} lines, which exceeds the {} line limit for {}",
                    file_name, line_count, threshold, file_type_desc
                ),
                Severity::Major,
                Category::CodeSmell,
                file_path,
                1,
            ).with_remediation(Remediation::substantial(
                format!(
                    "Consider splitting this file into smaller, focused modules. \
                    Each module should have a single responsibility. \
                    For {} lines, aim for files under {} lines each.",
                    line_count, threshold
                )
            )));
        }

        issues
    }
}

/// Check if the file content indicates it is generated
fn is_generated_file(source: &str, file_name: &str) -> bool {
    // Check file name patterns first (cheap check)
    for pattern in GENERATED_NAME_PATTERNS {
        if file_name.contains(pattern) {
            return true;
        }
    }

    // Check for generated markers in first 10 lines (common for generated headers)
    for line in source.lines().take(10) {
        let trimmed = line.trim();
        for marker in GENERATED_MARKERS {
            if trimmed.contains(marker) {
                return true;
            }
        }
    }

    false
}

/// Check if the file is a test file based on naming conventions
fn is_test_file(file_name: &str) -> bool {
    file_name.contains("_test")
        || file_name.contains("_tests")
        || file_name.ends_with("_test.rs")
        || file_name.ends_with("_tests.rs")
        || file_name.contains("test_")
        || file_name.starts_with("test_")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_s819_registered() {
        let rule = S819Rule::new();
        assert_eq!(rule.id(), "S819");
        assert!(rule.name().len() > 0);
        assert_eq!(rule.severity(), Severity::Major);
        assert_eq!(rule.category(), Category::CodeSmell);
    }

    #[test]
    fn test_is_test_file_detection() {
        assert!(is_test_file("foo_test.rs"));
        assert!(is_test_file("foo_tests.rs"));
        assert!(is_test_file("test_foo.rs"));
        assert!(is_test_file("foo_test_utils.rs"));
        assert!(is_test_file("_test_helper.rs"));
        assert!(!is_test_file("foo.rs"));
        assert!(!is_test_file("testing.rs"));
    }

    #[test]
    fn test_is_generated_file_detection() {
        // Generated markers
        assert!(is_generated_file("// GENERATED by protobuf", "foo.rs"));
        assert!(is_generated_file("# GENERATED FILE\nfn main() {}", "foo.rs"));
        assert!(is_generated_file("/* GENERATED */\nfn main() {}", "foo.rs"));

        // Generated name patterns
        assert!(is_generated_file("fn main() {}", "foo.pb.rs"));
        assert!(is_generated_file("fn main() {}", "foo.g.rs"));
        assert!(is_generated_file("fn main() {}", "foo_generated.rs"));

        // Not generated
        assert!(!is_generated_file("fn main() {}", "foo.rs"));
        assert!(!is_generated_file("fn main() {}", "foo_test.rs"));
    }

    #[test]
    fn test_s819_default_threshold() {
        let rule = S819Rule::new();
        assert_eq!(rule.threshold, 500);
        assert_eq!(rule.test_threshold, 800);
    }

    #[test]
    fn test_s819_custom_threshold() {
        let rule = S819Rule { threshold: 300, test_threshold: 500, ..Default::default() };
        assert_eq!(rule.threshold, 300);
        assert_eq!(rule.test_threshold, 500);
    }
}
