/**
 * `z.infer<typeof X>` re-exports for every schema in `schemas.ts`.
 *
 * The rule is: import `type X` from here, never re-derive from
 * `z.infer` in feature code. Keeps the public type surface obvious
 * and lets the schema module evolve without rippling.
 */
export type {
  GraphStatus,
  InspectableObjectType,
  RelationDirection,
  FindingSeverity,
  ArtifactFormat,
  LineRange,
  Property,
  ObjectIdentityEntry,
  EvidenceBlock,
  TypedRelation,
  WorkspaceSummary,
  ViewDescriptor,
  InspectableObjectSummary,
  SpotterResult,
  QualityIssueItem,
  QualityGateSummary,
  DesignFinding,
  QualitySeverity,
  SeverityCounts,
  QualitySummaryBlockBody,
  QualityIssueDetailBlockBody,
  LensDescriptor,
  LensResult,
  IdentityBlockBody,
  CallMetricsBlockBody,
  SignatureBlockBody,
  RelationItem,
  CallListBlockBody,
  SourceLine,
  SourceSliceBlockBody,
  SymbolQualityIdentityBlockBody,
  FileQualityIdentityBlockBody,
  ScopeQualityIdentityBlockBody,
  QualityGateBlockBody,
  IssuesListBlockBody,
  IssueIdentityBlockBody,
  IssueLocationBlockBody,
  IssueMessageBlockBody,
  RuleIdentityBlockBody,
  FileIdentityBlockBody,
  KindsBreakdownBlockBody,
  FileSymbolItem,
  FileSymbolsBlockBody,
  ScopeIdentityBlockBody,
  ScopeFilesBlockBody,
  CrossScopeEntry,
  CrossScopeBlockBody,
  HotspotItem,
  HotspotsBlockBody,
  ViewBlock,
  UnknownViewBlock,
  ViewBlockAny,
  ViewBlockBodyById,
  ContextualView,
  ExplorationColumn,
  ExplorationPath,
  OpenWorkspaceRequest,
  IndexWorkspaceRequest,
  SaveExplorationRequest,
  GenerateArtifactRequest,
  DecisionArtifactSummary,
  HealthResponse,
  AskResponse,
  GraphNode,
  GraphEdge,
  GraphNodeStyleClass,
  GraphEdgeStyleClass,
  SubgraphResponse,
  RationaleViewPayload,
  ContextualGraphResponse,
  ParentSection,
  ChildrenSection,
  SameLevelSection,
  // ---- multimodal (T17) ----
  NodeKind,
  EdgeKind,
  MultimodalNode,
  MultimodalEdge,
  GraphSearchResult,
  GraphSearchResponse,
  // ---- Landing Page (E4 ADR-039) ----
  GodNodeEntry,
  LandingPayload,
  // ---- Architecture View — E5 ADR-039 ----
  ArchitecturePayload,
} from "./schemas";

export {
  graphStatusSchema,
  inspectableObjectTypeSchema,
  relationDirectionSchema,
  findingSeveritySchema,
  artifactFormatSchema,
  lineRangeSchema,
  propertySchema,
  objectIdentityEntrySchema,
  evidenceBlockSchema,
  typedRelationSchema,
  workspaceSummarySchema,
  viewDescriptorSchema,
  inspectableObjectSummarySchema,
  spotterResultSchema,
  qualityIssueItemSchema,
  qualityGateSummarySchema,
  designFindingSchema,
  qualitySeveritySchema,
  lensDescriptorSchema,
  lensResultSchema,
  contextualViewSchema,
  explorationColumnSchema,
  explorationPathSchema,
  openWorkspaceRequestSchema,
  indexWorkspaceRequestSchema,
  saveExplorationRequestSchema,
  generateArtifactRequestSchema,
  decisionArtifactSummarySchema,
  healthResponseSchema,
  askResponseSchema,
  viewBlockSchema,
  viewBlockAnySchema,
  unknownViewBlockSchema,
  graphNodeSchema,
  graphEdgeSchema,
  graphNodeStyleClassSchema,
  graphEdgeStyleClassSchema,
  subgraphResponseSchema,
  rationaleViewPayloadSchema,
  contextualGraphResponseSchema,
  parentSectionSchema,
  childrenSectionSchema,
  sameLevelSectionSchema,
  // ---- multimodal (T17) ----
  nodeKindSchema,
  edgeKindSchema,
  multimodalNodeSchema,
  multimodalEdgeSchema,
  graphSearchResultSchema,
  graphSearchResponseSchema,
  // ---- Landing Page (E4 ADR-039) ----
  godNodeEntrySchema,
  landingPayloadSchema,
  // ---- Architecture View — E5 ADR-039 ----
  architecturePayloadSchema,
} from "./schemas";
