//! Input Validation Security Rules
//!
//! This module contains rules for detecting input validation vulnerabilities
//! including SQL injection, command injection, XSS, path traversal, and more.

pub mod command_injection;
pub mod deserialization;
pub mod http_splitting;
pub mod integer_overflow;
// TEMPORARILY DISABLED - ldap_injection has scope issues
// pub mod ldap_injection;
pub mod missing_sanitization;
pub mod open_redirect;
pub mod path_equivalence;
pub mod path_traversal;
pub mod sqli_injection;
pub mod trusting_url;
pub mod xpath_injection;
pub mod xss;
pub mod xxe;

// Re-export rule structs (generated by declare_rule! macro with pattern {ID}Rule)
pub use command_injection::S4721Rule;
pub use command_injection::S4721_AGENT_SEMANTICS;
pub use deserialization::S5042Rule;
pub use deserialization::S5042_AGENT_SEMANTICS;
pub use http_splitting::S2004Rule;
pub use http_splitting::S2004_AGENT_SEMANTICS;
pub use integer_overflow::S1155Rule;
pub use integer_overflow::S1155_AGENT_SEMANTICS;
// TEMPORARILY DISABLED - ldap_injection has scope issues
// pub use ldap_injection::S4811Rule;
// pub use ldap_injection::S4811_AGENT_SEMANTICS;
pub use missing_sanitization::S5130Rule;
pub use missing_sanitization::S5130_AGENT_SEMANTICS;
pub use open_redirect::S5696Rule;
pub use open_redirect::S5696_AGENT_SEMANTICS;
pub use path_equivalence::S5693Rule;
pub use path_equivalence::S5693_AGENT_SEMANTICS;
pub use path_traversal::S2591Rule;
pub use path_traversal::S2591_AGENT_SEMANTICS;
pub use sqli_injection::S3649Rule;
pub use sqli_injection::S3649_AGENT_SEMANTICS;
pub use trusting_url::S5732Rule;
pub use trusting_url::S5732_AGENT_SEMANTICS;
pub use xpath_injection::S4813Rule;
pub use xpath_injection::S4813_AGENT_SEMANTICS;
pub use xss::S5247Rule;
pub use xss::S5247_AGENT_SEMANTICS;
pub use xxe::S2755Rule;
pub use xxe::S2755_AGENT_SEMANTICS;
